### ISSUE TITLE
Comments not aligned after the line length(80) & declarations surpassing the line length(80)

### ISSUE THREAD

**Issue by FirdousP** [SAP/abap-cleaner#100]
Hi ,

Issue1:The constant declaration/code surpasses the 80 line length.
![image](https://github.com/SAP/abap-cleaner/assets/141395854/a529e48b-4ea3-46bd-9dec-b622a0a68615)

Expectation:
When any code written exceeds 80, it should ideally be in next line.

Issue 2: The comments are not aligned properly.
![image](https://github.com/SAP/abap-cleaner/assets/141395854/53abd82b-f7c8-4b6c-a995-dff9bcb72f0f)

Expectation:
The comment though written before or after the line length should all be aligned.
![image](https://github.com/SAP/abap-cleaner/assets/141395854/dfddaf83-9627-4e16-9378-54262c8997c8)

**Comment by jmgrassau** [comment]
Hi FirdousP, 

I do see your point, but unfortunately, this is currently a limitation of the tabular alignment in ABAP cleaner: In the cleanup rule "Align declarations", the recently added option…

![image](https://github.com/SAP/abap-cleaner/assets/79639298/d8b93dac-8f4a-4242-8e05-475510a8ccc8)

… only works if the VALUE clause is the last "column" of the to-be-aligned "table". In the case of your example, the line-end comments would be another "column", and that's why the VALUE can't be moved. I shall add some documentation on this:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/ef3d2510-d5f3-4b2d-bd91-ac20a432803e)

Regarding issue 2, this is out of scope, because as far as I can see from your second screenshot, these are inline declarations, while the "Align declarations" rule only processes upfront declarations. There is currently no general cleanup rule for exceeded line length or for alignment of line-end comments.

Kind regards,
Jörg-Michael

**Comment by ConjuringCoffee** [comment]
Adding to the topic of issue 2: Comments at the end of lines are considered bad practice by the Clean ABAP style guide:

https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md#put-comments-before-the-statement-they-relate-to

**Comment by jmgrassau** [comment]
Hi FirdousP, 

sorry there is no better solution for this at the moment – but nevertheless thanks, and at least this limitation is now documented.

Kind regards,
Jörg-Michael
