### ISSUE TITLE
"Replace CREATE OBJECT with NEW constructor" leads syntax error in Release 7.31

### ISSUE THREAD

**Issue by DirkBor** [SAP/abap-cleaner#119]
In the ABAP Cleaner, 7.50 can be selected as the lowest ABAP release.
At the moment we are mainly working on a 7.31 release.
The rule "Replace CREATE OBJECT with NEW constructor" is used as default.
I have to switch off this rule, because otherwise this rule generates a statement, which leads to a syntax error in our release (7.31).

**Comment by jmgrassau** [comment]
Hi DirkBor, 

thank you very much for reporting this! I now did some more research on when exactly the NEW operator was introduced (in 7.40 SP2), and whether further restrictions must be added for other cleanup rules. Looks like we're now fine down to version 7.02 = 7.0, EhP2. Cleanup rules that merely "react" on newer syntax such as ABAP Doc, VALUE constructors etc. are no problem; restrictions must only be defined for cleanup rules that _introduce_ newer syntax to the code. 

So, older releases starting from 7.02 were added on the UI …

![image](https://github.com/SAP/abap-cleaner/assets/79639298/c6fe5db7-e098-4b60-814b-df4285f3ef00)

… and a restriction was added to the rule "Replace CREATE OBJECT with NEW constructor"

![image](https://github.com/SAP/abap-cleaner/assets/79639298/406adcf6-cf0c-4599-a1d3-24d73a51e8bf)

… to automatically deactivate it if an older release was detected in the code, or selected on the UI.

With that, the issue should be fixed with the next ABAP cleaner release!

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi DirkBor, 

thanks again for opening this issue! Added support for ABAP 7.02…7.42 is now part of ABAP cleaner version 1.6.0, which was just released. I hope we now have all restrictions down to ABAP 7.02 defined correctly; if you encounter any new issues on ABAP 7.31, please let us know! 

Kind regards,
Jörg-Michael
