### ISSUE TITLE
Unchain into multiple statements does not apply to interfaces

### ISSUE THREAD

**Issue by fabianlupa** [SAP/abap-cleaner#12]
The rule "Unchain into multiple statements" breaks up my method definition chained statement in classes in multiple statements. It does however not apply to method definitions in interfaces and I do not see a way to turn it on either. This seems inconsistent.

**Comment by jmgrassau** [comment]
Hi Fabian, 

you're right, thanks for pointing this out! This will be fixed in the next release (version 1.2), where I added a new option to the "Unchain into multiple statements" rule:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/9b37e33a-72fe-4c9a-8f73-79fc3dfb71f9)

This is active by default, but since this comes with an update, you might have to activate it manually, depending on this option on profile level:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/83c846ed-6a53-453b-8be9-ba8ebc5a4e5b)

Kind regards,
Jörg-Michael
