### ISSUE TITLE
Question: is there a mechanism to prevent cleanup of certain legacy includes or code sections?

### ISSUE THREAD

**Issue by vonglan** [SAP/abap-cleaner#121]
For example with a pseudo-comment / tag

Disclaimer: I am a brand-new user, so I am not yet sure how important such a feature would be

**Comment by jmgrassau** [comment]
Hi Edo, 

so far, there are no pseudo-comments for ABAP cleaner, simply because I don't think anyone would want yet another set of them (already having ```##PRAGMA```, ```"#EC ...```, ```"#EC CI_...``` etc.). 

However, my impression is that indeed such pseudo-comments or tags are not needed yet, because the cleanup rules always check whether an ABAP statement matches the "expected syntax" before they apply any changes to it. Therefore, if a statement is in some way unexpected (because of obsolete syntax, comments in weird places, unorthodox coding style etc.), the cleanup rules would simply leave that statement unchanged. 

Also, cleanup rules that introduce newer ABAP syntax (such as ```+=``` assignment operators, or ```NEW``` operators) are automatically skipped if the code belongs to an older ABAP release which does not support these constructs. 

Nevertheless, this may be worth some remarks in the documentation! And if you come across concrete examples, please let us know. Maybe some cases could also be solved with additional options that specifically exclude certain older syntax or contexts etc. 

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi Edo, 

I now added a section in the documentation for the Main Window:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/0dc2a2d6-70a3-4380-a70c-4d8fce6bb469)

Hope this approach continues to work! The ideal case would be that after some initial selection and configuration of the cleanup rules, users of ABAP cleaner can be sure that whenever they press Ctrl+4, their code gets better (or at least not worse), without them having to check the changes. Where that's not the case, we'd continue to fine-tune the cleanup rules. 

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi Edo, 

thanks for opening this issue! The enhanced documentation was now added to this repo. (Not expecting everyone to read all documentation first, but at least now we have a place to point to if the question comes up again :-)

Kind regards,
Jörg-Michael

**Comment by vonglan** [comment]
Hi Jörg-Michael,

that is a good decision about pseudo-comments.

My intended use case was a different one (but as I wrote: I am not yet sure whether it turns out to be relevant in practice):

When a developer (especially in an SAP customer context) does not want "his" code to be "improved" by others.
For example, we have had a case where an external developer completely refactored (manually) the code of an internal developer, which lead to some (avoidable) negative emotions.

Because using ABAP Cleaner is so quick and easy, developers might always use it whenever they change a single line of "someone else's" coding.
Of course, this can also be addressed via a section in the Coding Guideline "How to use ABAP Cleaner".

I will contact you again, if this turns out to be an important use case for us.

Thanks,
Edo

**Comment by jmgrassau** [comment]
Hi Edo, 

thanks for the explanation. Yes, I'd also say this is rather a case for internal alignment or guidance ("How to use ABAP cleaner") than for a pseudo-comment that "protects" code from being processed with ABAP cleaner. Anyway, that well-meaning, overeager external developer would soon discover how to remove such a pseudo-comment…

Kind regards,
Jörg-Michael
