### ISSUE TITLE
Question: Why is "rearrange local declarations" not in default profile?

### ISSUE THREAD

**Issue by vonglan** [SAP/abap-cleaner#122]
Is it because some people like "pseudo-local" declarations in blocks, like in the example in line 24+25?

Then a configuration "Keep declarations at beginning of blocks" would be useful.
A block would be a LOOP or IF.

**Comment by jmgrassau** [comment]
Hi Edo, 

actually, such "pseudo-local" declarations would even be supported by this cleanup rule: if you configure it like this …

![image](https://github.com/SAP/abap-cleaner/assets/79639298/4b09435a-3085-4f86-a1d2-faa5e1a698d5)

… then variables will be actively moved into the innermost block in which they are (exclusively) used:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/4ef6ad7e-17b4-42bc-a4c3-db0bf4087b91)

This is discouraged from Clean ABAP point of view, but might actually help to analyze a long method and extract parts from it to dedicated methods. 

The rule is not activated by default because the feeling was that some people might find it a bit "invasive". Therefore, for a rule that potentially reorders dozens of lines in a long method, an "opt-in" approach seemed more appropriate. 

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi Edo, 

hope this helps as an answer for your question, so closing this for now! (But for sure, decisions on what should or shouldn't be the default always leave room for discussion.)

Kind regards,
Jörg-Michael

**Comment by vonglan** [comment]
ok, thanks!
