### ISSUE TITLE
Feature request (or bug?): Rule: "Standardize empty line within methods" should be able to eliminate (all) blank lines

### ISSUE THREAD

**Issue by JoachimRees** [SAP/abap-cleaner#131]
The rule "Standardize empty line within methods" should be able to eliminate **all** blank lines.
As of now, this (example from abap cleaner) is the shortest I seem to be able to get:

```
  METHOD empty_lines_within_methods.
    DATA lv_any_integer TYPE i.
    DATA lv_any_string  TYPE string.
    do_something( ).

    do_something_else( ).

    finish_doing_something( ).
  ENDMETHOD.
```

What I want ist this:

```
  METHOD empty_lines_within_methods.
    DATA lv_any_integer TYPE i.
    DATA lv_any_string  TYPE string.
    do_something( ).
    do_something_else( ).
    finish_doing_something( ).
  ENDMETHOD.
```

... Setting "Max empty lines within methods" to 0 might/would/should do exactly that. 
But I cannot set it to 0 -> it's always set back to 1 :-(  . 
![2023-10-04 16_13_05_ABAP_cleaner_Emty_Lines_0_not_Possible](https://github.com/SAP/abap-cleaner/assets/56995316/9e092252-2701-4541-9ac8-4ea10c183451)

**Comment by jmgrassau** [comment]
Hi Joachim, 

for each numeric input field, ABAP cleaner defines a range for possible input – you can try that by pressing Ctrl+Pos1 and Ctrl+End inside each of these fields (also Arrow Up/Down and Page Up/Down works). 

In this case, entering "Max. empty lines within methods" = 0 would mean that inside methods, ABAP cleaner would remove all empty lines in all cases. I simply didn't expect that someone would want that, because wouldn't you agree that there can be good reasons to structure a method into sections with the help of empty lines? So there could be empty lines that were intentionally put there and you wouldn't want to remove them? 

The styleguide says "[Add a single blank line to separate things, but not more](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md#add-a-single-blank-line-to-separate-things-but-not-more)", and even in your short example, I'd personally prefer an empty line between the declarations and the executable statements. 

But if you're sure you want to get rid of all empty lines, it would be very easy to allow a 0 here. 

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi Joachim, 

sure, that's easily done:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/bf4f218b-0df5-4836-b139-83249b2d6812)

With respect to the anti-pattern: What ABAP cleaner can do is remove the line breaks at the start and at the end of the method, because IMHO that always makes sense. It can also reduce multiple line breaks to just one. So, from this code…

```ABAP
METHOD do_something.

  do_this( ).


  then_that( ).

ENDMETHOD.
```

…you would then get:

```ABAP
METHOD do_something.
  do_this( ).

  then_that( ).
ENDMETHOD.
```

However, what ABAP cleaner can't do is decide whether the remaining line break is intentional and should therefore be kept. That would require a human being looking at what the code does and whether it helps readability to structure it into several sections with a blank line between them. (Well, you could introduce an option that says "if my method only consists of a maximum of [3] lines, then always remove all blank lines). 

So, I guess this is a limitation of the approach ABAP cleaner has: 
* In [ABAPQuickFix](https://github.com/fidley/ABAPQuickFix), you select a section of code, then the tool offers you the quick fixes available for that section, and then you explicitly select which fixes you want applied for that particular section. That's much more interaction, but it means that ABAPQuickFix can offer refactorings that make sense in some places, but wouldn't in others (such as "Remove all comments"). 
* ABAP cleaner, on the other hand, once you've configured it, automatically executes all cleanup rules on all code, so you don't interact with it each time, saying "remove the empty lines here, but not there". With this, all is done in just one click, but on the other hand, ABAP cleaner must be able to automatically determine what to do, otherwise it can't do it. 

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi Joachim, 

version 1.7.0 now allows to set this option to 0!

Kind regards,
Jörg-Michael
