### ISSUE TITLE
Get an error when query to ABAP CDS contains read by association

### ISSUE THREAD

**Issue by Kronrir** [SAP/abap-cleaner#133]
Hello!
I've used ABAPCleaner for last 3 months and that is super cool tool thank you a lot!
I found one bug when I tried to clean/format piece of code which contains select by association in ABAP CDS view.
Error you can see at the screenshot
![image](https://github.com/SAP/abap-cleaner/assets/147395465/0f734688-b14b-485b-9274-0aa949377ded)
I can't refactor this command it is usual read by association for me.
Maybe somebody can suggest how to refactor such code, but I think that is a bug.

**Comment by jmgrassau** [comment]
Hi Kronrir, 

thanks for opening this issue! Actually this error is just about the colon ":" inside the brackets ```[ ... INNER : WHERE ... ]```, so "refactoring" would simply mean to remove this colon, getting ```[ ... INNER WHERE ... ]```.

With such a colon, you could do things like this:

```ABAP
    CONSTANTS lc_id1 TYPE s_conn_id VALUE '1234'.
    CONSTANTS lc_id2 TYPE s_conn_id VALUE '5678'.

    SELECT \_spfli[ (1) INNER WHERE : 
         connid > @lc_id1 ]-connid AS connid FROM demo_cds_assoc_scarr AS scarr INTO @DATA(result1),  
         connid < @lc_id2 ]-connid AS connid FROM demo_cds_assoc_scarr AS scarr INTO @DATA(result2).
        " do something with result1 and result2
      ENDSELECT.
    ENDSELECT.
```

So you'd have one opening ```[```, but two closing ```]```, and one ```SELECT```, but two ```ENDSELECT```, and that would be very hard for ABAP cleaner to process (and for humans to read). 

However, strictly speaking, in _this_ case, the colon doesn't harm so much, because there is no comma, therefore it is just a "chain with one element" and the opening bracket is only closed once. I shall adjust ABAP cleaner to accept these cases. Nevertheless, I think there is no reason to have this colon here. 

Kind regards,
Jörg-Michael

**Comment by Kronrir** [comment]
Ok, agree with you in _this_ case I reworked query and read data directly from CDS which is associated from root CDS, that was not a problem. 
It will be nice if ABAP cleaner can process that colon correctly because sometimes read by association very helpfull.
Thank you.

**Comment by jmgrassau** [comment]
Hi Kronir, 

I am not sure whether I understand you point: How does removing the chain colon change the way how data is read here? From what I see in the ABAP documentation on [attributes in Path Expressions](https://help.sap.com/doc/abapdocu_latest_index_htm/latest/en-US/abenabap_sql_path_filter.htm), there is no need to put a colon between INNER and WHERE. 

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi Kronrir, 

thanks again for bringing this up – in version 1.7.0, which was just released, ABAP cleaner now "tolerates" chain colons inside of parentheses and brackets if no comma is found (i.e. in "chain of one" cases), so your example above wouldn't trigger a "parse error" anymore. 

Kind regards,
Jörg-Michael
