### ISSUE TITLE
What happens when you use an old ABAP Cleaner version with a new profile?

### ISSUE THREAD

**Issue by ConjuringCoffee** [SAP/abap-cleaner#140]
Hi Jörg-Michael 🙂 The profile stores a `requiredVersion` and a `programVersion`. What will happen if someone has a team profile that has higher versions than what is currently installed?

**Comment by jmgrassau** [comment]
Hi ConjuringCoffee, 

nice question – you can try it out by using a text editor to change requiredVersion to e.g. 999 :-) Note that this is a "technical version" (currently 23) which is not in sync with the product version (currently 1.7.1). The technical version is only increased when file formats are changed or enhanced in a way that would cause data loss if the file was loaded and saved with an older release. With the first Open-Source release, it was 21, now it is 23. 

If a profile has a requiredVersion that is higher than the programVersion installed with one of the team members, this profile would simply not be loaded for this team member, and it would not appear in the list of profiles. If that profile had been selected as the current profile, the selection would fall back to the user's own "default" profile. When they update ABAP cleaner to the current version, it would be loaded and displayed again. 

Hm, I guess you will now ask me to add a meaningful error message here, right? ;-)

Kind regards,
Jörg-Michael

**Comment by ConjuringCoffee** [comment]
> Hm, I guess you will now ask me to add a meaningful error message here, right? ;-)

You're exactly right 😄

**Comment by jmgrassau** [comment]
Hi ConjuringCoffee, 

if #219 happens because the ABAP cleaner version of a user is outdated and therefore, a synchronized profile cannot be accessed (e.g. because another user with a newer ABAP cleaner version changed the profile), you will now see the following message:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/b039527d-7b2d-4383-a36d-d9f5c378da97)

After updating ABAP cleaner, the profile will "reappear" (but will then have to be actively selected again). Note, however, that these are technical versions, which change much less frequently than the release versions. As of now, even the oldest version of ABAP cleaner (technical version 1) could still read the current profiles format. 

Kind regards,
Jörg-Michael

**Comment by ConjuringCoffee** [comment]
Thank you!

**Comment by jmgrassau** [comment]
Hi ConjuringCoffee, 

this notification is now available with version 1.13.0!

Kind regards,
Jörg-Michael
