### ISSUE TITLE
Alignment of parameters with NEW statement not working

### ISSUE THREAD

**Issue by MagneeR** [SAP/abap-cleaner#153]
Hi!
I'm using the ABAP Cleaner tool and I realize that its not working as I expected with the NEW operator.

Original code and ABAP Cleaner return:
![image](https://github.com/SAP/abap-cleaner/assets/33860404/855fc3f8-213a-45f1-bbd6-6ae3ed304c47)

Expected result:
![image](https://github.com/SAP/abap-cleaner/assets/33860404/8a5538ca-0b84-4643-877e-32cc79f86f13)

Can you add a new rule for this? 
Thank you!

**Comment by ConjuringCoffee** [comment]
You can already use rule "Align parameters and components" to achieve this. 😉

Here's the settings I am personally using to achieve that result:

![image](https://github.com/SAP/abap-cleaner/assets/72548231/2f45b8a5-0d27-47c5-baa6-d79949df9d98)

**Comment by fabianlupa** [comment]
As [the styleguide](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md#line-break-multiple-parameters) explicitly demands to break parameters I would have assumed the necessary options are both activated in the default ("going _beyond_ the guide") and essential ("explicitly demanded by the guide") profile. I also checked normal method calls which aren't cleaned with line breaks either.

**Comment by MagneeR** [comment]
I was trying to aplly @ConjuringCoffee settings but i can't select any rule. Any idea of what to do to fix it?
Maybe reinstalling ABAP Cleaner?
![image](https://github.com/SAP/abap-cleaner/assets/33860404/3581c81f-3f94-4d4b-9f89-b2688ea44758)
Thank you for your help!

**Comment by jmgrassau** [comment]
Hi MagneeR, 

that's really odd, I've never seen this. Seems like the rules list is minimized rather than grabbing all (vertical) space that it gets. What happens if you change the size of this window? Which OS and which Java / SapMachine version are you using? 

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
P.S.: Apart from that, this is the same as in #154: Things are kept on one line because of this option:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/b7746d55-f335-44cf-9590-705d44d4b601)

which should not happen in this case, because it is not a table row. 

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi MagneeR, 

thanks for reporting this issue with the NEW operator, as well as #154. This will be fixed in the next release, meaning that regardless of the setting for "Table rows: Keep multiple components on single line", line breaks will be introduced to non-table-rows cases, as they should:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/b409b360-4dd1-4c10-8dde-336ac3b08c6b)

Kind regards,
Jörg-Michael

**Comment by MagneeR** [comment]
Hi Jörg-Michael,
That's perfect! 😄 

You are doing a great job.
Thank you very much!

**Comment by ConjuringCoffee** [comment]
I didn't even know I wanted that, great 😁

**Comment by jmgrassau** [comment]
Hi MagneeR, 

thanks again for pointing this out – this should now be fixed in version 1.8.0, which was just released!

Kind regards,
Jörg-Michael
