### ISSUE TITLE
Alignment of components inside VALUE operator not working

### ISSUE THREAD

**Issue by MagneeR** [SAP/abap-cleaner#154]
Hi!
I've just found that ABAP Cleaner isn't aligning the components inside the VALUE operator.

Original code and ABAP Cleaner result:
![image](https://github.com/SAP/abap-cleaner/assets/33860404/f40bd43e-1fc2-431a-a09a-9104c594e849)

Expected result:
![image](https://github.com/SAP/abap-cleaner/assets/33860404/f1a58210-417b-46fb-ace2-7f51e586fed9)

Is it possible to create a rule for this case?
Thank you!

**Comment by ConjuringCoffee** [comment]
Your examples are easier to check if you include them as source code 😉

```abap
TYPES:
  BEGIN OF numbers,
    n1 TYPE n,
    n2 TYPE n,
    n3 TYPE n,
  END OF numbers.

DATA(ls_numbers) = VALUE numbers( n1 = '01' n2 = '02' n3 = '03' ).
DATA(ls_numbers_reverse) = VALUE numbers( BASE ls_numbers n1 = '02' n3 = '01' ).
```

I think most of your request already works with rule "Align parameters and components". Only the `BASE` case doesn't seem to work how you want it to:

```abap
DATA(ls_numbers) = VALUE numbers( n1 = '01'
                                  n2 = '02'
                                  n3 = '03' ).
DATA(ls_numbers_reverse) = VALUE numbers( BASE ls_numbers n1 = '02'
                                          n3 = '01' ).
```

**Comment by jmgrassau** [comment]
Hi MagneeR, 

exactly, as ConjuringCoffee showed, it is this setting that does the trick:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/5870566d-2918-4ec3-8753-46a38fa365e2)

However, you still have a point here, because this option was originally meant for table rows (hence the name), as shown in the example:

```ABAP
    mts_table = VALUE #( ( item_key = '20220030000101'  event_date = '20220301'  total_qty = '30'  qty_unit = 'DAY'  amount = '1000.00'  currency = 'EUR' )
                         ( item_key = '20220040000101'  event_date = '20220401'  total_qty = '30'  qty_unit = 'DAY'  amount = '1500.00'  currency = 'EUR' )
                         ( item_key = '20220050000101'  event_date = '20220501'  total_qty = '30'  qty_unit = 'DAY'  amount = '2000.00'  currency = 'EUR' ) ).
```

The thought behind this is that with multiple of such rows, you get a "tabular" style which is very nice to read, even if it exceeds line length a bit. However that's never the case with structures as in your example, so actually there is no point in keeping those on one line, and this setting should not cover them. 

Kind regards,
Jörg-Michael

**Comment by MagneeR** [comment]
Thank you both of you!
