### ISSUE TITLE
Feature request: separate hotkeys in eclipse for different cleanup ranges

### ISSUE THREAD

**Issue by Lightirius** [SAP/abap-cleaner#164]
Hi.
I would like to have separate hotkeys at least for this cleanup ranges;
* Entire code document
* Current method etc.
My use cases are:
* While editing a global class I don't want to clean up everything, because it can potentially interfere with someone elses work
* While editing anything but global class - I want to clean up everything

Right now it is quite cumbersome to switch betwen this use-cases. You need to remember current default cleanup range settings and change them a lot

With the default ABAP pretty printer It is possible.

**Comment by jmgrassau** [comment]
Hi Lightirius, 

the bottleneck here is the availability of good, easy-to-remember hotkeys in ADT (just give it a try, looking at Window -> Preferences -> General -> Keys -> sort by "Binding"), esp. if you want a pair of them for automated/interactive cleanup. Even Ctrl+4 / Shift+Ctrl+4 is not ideal, because on some macOS versions, Shift+Ctrl+4 is reserved by the OS (for screenshots, if I am not mistaken). Also, each shortcut would usually come with a menu item, or rather 2-3 of them for automated / interactive / preview, so we'd either get a long list of menu items, or submenus, which would then mean to always have an extra click for users who prefer menus. 

Nevertheless, your use cases are interesting (and completely make sense from the perspective of "number of objects locked on my transport"): It would of course be easy for ABAP cleaner to identify a global class (starting with CLASS … DEFINITION … PUBLIC), so maybe splitting this option on the UI ("Default cleanup range for global classes: …" / "Default cleanup range otherwise(?): …") would do the trick? 

Kind regards,
Jörg-Michael

P.S.: Apart from that, with the current situation, I'd personally not change (and each time try to remember) the cleanup range settings, but rather keep "Current method" and use Ctrl+4 inside global classes, but Ctrl+A, Ctrl+4 everywhere else.

**Comment by Lightirius** [comment]
Hi @jmgrassau 
I didn't know that ctrl+4 works for selected text. That mostly solves my problem. It's not ideal, but a lot better.

As for the default hotkeys - I don't see anything wrong if specific ones like "format current method" "format entire document" are not bound by default and are not present in menus. They are, well, specific. In my opinion it is enough to document that they exist and you can bind them. 
I am not shure what is the default setting for ctrl+4 right now, but if it is "format current method", then ctrl+alt+4 may be a decent default option for "format entire document" (or vice versa)

Extra default config option for global classes is not Ideal, because for newly created classes you may still need/want to format all

Personally i'd set ctrl+4 to format current method, ctrl+shift+4 to format all and use ctrl+3 to find extra options if I need something special. I don't think thant current defaults are bad, they are just not Ideal for me.

**Comment by jmgrassau** [comment]
Hi Lightirius, 

> That mostly solves my problem.

that's good to hear! Yes, if any range of statements is selected, ABAP cleaner will process exactly those statements (only expanding the selection to full statements). The "Default cleanup range" is only used if nothing is selected; and I think you can press Ctrl+A, Ctrl+4 almost as fast as you could Ctrl+Alt+4 (which I'd find a bit un-ergonomic). 

So I think I'd close this for now. As you can see, the available "commands" are currently independent of the cleanup range (because that's configured on the UI) …

![image](https://github.com/SAP/abap-cleaner/assets/79639298/77af066d-2c2c-423a-8714-5106db6dacdd)

… and introducing new commands – even without default key binding or menu – would multiply them ("Clean Up Entire Document With Automated ABAP Cleaner", "Clean Up Entire Document With Interactive ABAP Cleaner…", "Show Read-Only Preview of Entire Document With ABAP Cleaner…"). 

Kind regards,
Jörg-Michael

**Comment by ConjuringCoffee** [comment]
Hi Jörg-Michael, have you thought about using shortcuts that are executed after each other? Take the shortcuts using CTRL+2 as an example. You need to press a letter key after CTRL+2 to decide which shortcut should be executed. Maybe this would be an approach you can use?

![image](https://github.com/SAP/abap-cleaner/assets/72548231/0de1ccbf-4422-4e78-ba26-6ae5ac3fd4bb)
