### ISSUE TITLE
Discussion: Macro and new features

### ISSUE THREAD

**Issue by duytai800** [SAP/abap-cleaner#172]
Jörg-Michael, hi! I'd like to discuss three issues with you. I am grateful for your assistance.
1. Macro: This macro code is not working with the clean up rules that I want to apply. Despite this, there are no issues with the code. I'm curious if it's something else or just my poor code writing. I am grateful for your support.
![image](https://github.com/SAP/abap-cleaner/assets/77057189/9add45f7-cd78-4b8a-b8f9-e61feb303f40)
2. Apply rules to project: Is it possible to apply clean-up rules to the entire project? At the moment, I can only apply clean-up rules to a single file, and I hope we can change that. 
3. The old system: At the moment, there are some projects created on the previous system, thus there are some circumstances where we can not apply the clean up rules. How should I handle these situations?

**Comment by jmgrassau** [comment]
Hi Tài, 

ad 1: your code is fine and you're not doing anything wrong here – this is just a limitation of ABAP cleaner which would be very difficult to overcome. Therefore the message says "not supported", and I hope this case doesn't come up too often. 

More precisely, a macro definition can contain incomplete code blocks such as an opening IF without an ENDIF…

```ABAP
  DEFINE check_initial.
    IF &1 IS INITIAL.
  END-OF-DEFINITION.
```

and using that macro would also lead to incomplete code blocks (3x closing ENDIF with no opening IF visible): 

```ABAP
  check_initial lv_any.
  check_initial lv_other.
  check_initial lv_third.
      ENDIF.
    ENDIF.
  ENDIF.
```

This can be handled by a compiler by inserting the macro definition 3 times, but ABAP cleaner has no mechanism for this (and in some cases can't have it, because the macro definition might be "out of sight" for ABAP cleaner). 

In the parser implemented in ABAP cleaner, WHEN is a bit of a special case, because it opens a block (next line is indented further) and at the same time closes the previous WHEN (a bit like ELSEIF), until the last WHEN is closed with ENDCASE. So, things would work if you extracted the "WHEN &1" line from the macro:

```ABAP
  DEFINE call_again.
    IF &1 IS NOT INITIAL.
      ...
    ENDIF.
  END-OF-DEFINITION.
```

and used it like this:

```ABAP
  CASE ....
    WHEN 1.
      call_again lv_any.
    WHEN 2.
      call_again lv_other.
  ENDCASE.
```

But that would be a workaround for the sake of ABAP cleaner, which may not be a good idea.

ad 2: No, there is currently no mechanism for that, either. ABAP cleaner runs completely locally on your machine, getting the code from ADT, and returning the changed code to it, so the entire handling of changes (on your transport) is left to ADT. You may, however, want to check whether the section [Calling ABAP cleaner from the Command Line](https://github.com/SAP/abap-cleaner/blob/main/docs/usage.md#calling-abap-cleaner-from-the-command-line) could help in your setup and workflow. 

ad 3: Not sure what you mean here, what circumstances do you have in mind? If this is about older ABAP releases which don't yet support newer ABAP syntax, that could be covered by this setting on the ABAP cleaner UI:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/ee392d92-583f-4590-8b9b-62215102c90e)

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi Tài,

sorry I had no better news that "out of scope" here, but these are indeed technical limitations of how ABAP cleaner is implemented, so closing this for now. 

Kind regards,
Jörg-Michael
