### ISSUE TITLE
Bug: ABAP-Cleaner uses CRLF instead of LF

### ISSUE THREAD

**Issue by fmabap** [SAP/abap-cleaner#177]
Hello,
I’m working on project where I generate ABAP code with Yeoman. I want to use ABAP-Cleaner command line tool to format the generated code.

The generated code will be uploaded with abapGit as ZIP-File (offline repository) into the SAP-System.
Unfortunately adds the ABAP-Cleaner at the end of each line a CRLF instead of a LF. The coding cannot be deserialized with this.
I’m getting the following error in abapGit.

<img width="354" alt="Error" src="https://github.com/SAP/abap-cleaner/assets/101019006/e6d734b1-34f1-4812-942a-4856f176c2f1">

You can see it in the debugging of the method ZCL_ABAPGIT_OBJECT_CLAS->DESERIALIZE_ABAP variable LT_SOURCE.

<img width="941" alt="crlf" src="https://github.com/SAP/abap-cleaner/assets/101019006/63bcabe7-7a7f-4786-b506-0dba450ad6d7">

I created a test class with the SE80 for demonstration. I exported it as ZIP file (original.zip) with the abapGit and applied the ABAP-Cleaner on it (cleaned.zip).

[cleaned.zip](https://github.com/SAP/abap-cleaner/files/13201155/cleaned.zip)
[original.zip](https://github.com/SAP/abap-cleaner/files/13201157/original.zip)

Can you please change the CRLF to LF?

Best regards
Frank

**Comment by jmgrassau** [comment]
Hi Frank, 

maybe a solution as in #124 is possible, where @stockbal used ```git config --global core.autocrlf true``` to help Git cope with the CRLF? (cp. his workflow shown in [GitHub Actions workflow usage](https://github.com/SAP/abap-cleaner/blob/main/docs/usage.md#github-actions-workflow-usage))

Inside ADT, the code is passed to ABAP cleaner with CRLF (at least on Windows), which is why I originally chose to return it that way, too: 

![image](https://github.com/SAP/abap-cleaner/assets/79639298/8ac7fc9a-1466-4a8e-9720-2e89b56dbf4c)

But maybe the best solution for the command line case would be to add a parameter that allows you to select whether you'd like the code to be returned with CRLF or LF – or alternatively, auto-detecting from the input code? (However, this would only work if code documents with only one line end with a line break).

Kind regards,
Jörg-Michael

**Comment by stockbal** [comment]
Hi Jörg-Michael,

I don't think the git config is a solution here. If I understand Frank correctly he just zip's the local abapGit repo after it was processed via ABAP Cleaner and then uploads it into the SAP system.  
Therefore no commit is executed and git did replace the the `crlf` with `lf` line endings.

A custom cli option to control the line endings would be the best solution in my opinion.

Regards,
Ludwig

**Comment by jmgrassau** [comment]
Hi Ludwig, 

ah, understood, thanks! So probably, since LF seems to be preferred, this command line option could be ```--crlf```, and without it, LF should be used as a default? That would change the behavior, but I guess ```git config --global core.autocrlf true``` would continue to work either way, right?

Kind regards,
Jörg-Michael

**Comment by stockbal** [comment]
Hi Jörg-Michael,

yes, the git line feed conversion should still work

Kind regards,
Ludwig

**Comment by jmgrassau** [comment]
Hi Frank and Ludwig, 

thanks for reporting and discussing this issue! In version 1.10.0, which was just released, the cleanup from command line now uses LF as the default, but offers the new option ```--crlf``` if CRLF should ever be needed by someone. Documentation was enhanced accordingly. 

Kind regards,
Jörg-Michael
