### ISSUE TITLE
CANCEL-button placement inconsistent

### ISSUE THREAD

**Issue by VladGhitulescu** [SAP/abap-cleaner#188]
Hey,

the CANCEL-button is placed both on the left and right side (see the attached screenshots) which leads to accidental clicks on the wrong button.

![CleanShot 2023-11-09 at 05 50 55@2x](https://github.com/SAP/abap-cleaner/assets/3112128/d8209f41-a5ec-43c3-949a-1d7481cf8e8a)

![CleanShot 2023-11-09 at 05 51 39@2x](https://github.com/SAP/abap-cleaner/assets/3112128/2ec74815-98ef-46f7-a42b-98b13dedc908)

On the Mac the default position for CANCEL is on the left (see again the attached screenshots).

![CleanShot 2023-11-09 at 05 53 35@2x](https://github.com/SAP/abap-cleaner/assets/3112128/c6c918b1-189e-4a1a-b07e-a12390d79714)
![CleanShot 2023-11-09 at 05 53 05@2x](https://github.com/SAP/abap-cleaner/assets/3112128/7222f118-2721-4ed7-b3ef-632b35d4ae2e)

Regards,
Vlad

**Comment by jmgrassau** [comment]
Hi Vlad, 

ah, good point! Of course this should be consistent at least within ABAP cleaner. Not sure about the best order, though, for example MS Word (on Windows) would give me:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/19636ab1-3e41-41b1-882a-808cccdd189b)

But since we are an ADT / Eclipse plug-in, I guess adjusting to ADT standards would be the best way to go. E.g., if I close an editor with an unsaved change, I get: 

![image](https://github.com/SAP/abap-cleaner/assets/79639298/e0d4fcec-4d1f-4314-9ef7-2b5f0391a79f)

Menu "Window / Preferences" shows:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/e29d4cbb-c655-441c-aab4-8defe00367d9)

A wizard like "File / New / ABAP Project" has:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/ac41d332-58ac-4483-b1d1-51a6fa2b4b5e)

Do you get the same on macOS or is that OS-specific?

Kind regards,
Jörg-Michael

**Comment by VladGhitulescu** [comment]
Hello again JM,


Eclipse align with the OS guidelines:

![CleanShot 2023-11-09 at 09 27 12](https://github.com/SAP/abap-cleaner/assets/3112128/940d1ff4-7404-45d8-8752-10d65fa10f2a)


Regards,
Vlad

**Comment by jmgrassau** [comment]
Hi Vlad, 

thanks again for opening this issue! With the next release, the order of OK / Cancel buttons should be in line with the respective OS standards, i.e. "OK – Cancel" for Windows, but "Cancel – OK" for macOS and Linux. 

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi Vlad, 

thanks again for taking such a close look at these buttons and their order – this should now be fixed with version 1.13.0, which was just released!

Kind regards,
Jörg-Michael
