### ISSUE TITLE
ABAP doc position on Interface constants

### ISSUE THREAD

**Issue by RicardoLadeiro** [SAP/abap-cleaner#204]
While formatting multiple constants on the same interface, ABAP cleaner reorganizes the ABAP doc position for those.
This is causing the constant description to unlink from the constant itself.

![image](https://github.com/SAP/abap-cleaner/assets/64472881/2037b4fa-ebec-4ac1-8062-e8610cbedaef)

**Comment by jmgrassau** [comment]
Hi Ricardo, 

thanks a lot for reporting this – you're right I overlooked that! This will be fixed with the next release, so if there is any ABAP Doc attached to the declaration, it will be kept behind the colon:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/89f3dc56-2f4c-4bee-b38f-420179fa6929)

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi Ricardo, 

thanks again for reporting this! This bug should now be fixed with version 1.11.2, which was just released!

Kind regards,
Jörg-Michael
