### ISSUE TITLE
Reasoning behind default value of "Indent of clause keywords"?

### ISSUE THREAD

**Issue by ConjuringCoffee** [SAP/abap-cleaner#214]
Hi Jörg-Michael, I'd like to discuss the option "Indent of clause keywords" for the rule "Align SELECT clauses". You've chosen the default value "add 2". The option additionally has the options "add 4" and "add 7".

The default profile comes with rule "Align keywords with second word of first line" being active. This would add seven spaces for the clause keywords in `SELECT`s. Personally, I agree with your choice of not having "add 7" as the default - it seems way too much here. 

What made you choose two spaces though? It seems contrary to the other decisions in the clean-up rules.

(Personally, my main reason against "add 2" is that you can confuse the line for the next level of statements or vice versa. Like in this example:)

```abap
    SELECT *
      FROM mara
      INTO @DATA(ls_mara).
      WRITE 'hello'.
    ENDSELECT.
```

**Comment by jmgrassau** [comment]
Hi ConjuringCoffee, 

nice example :-) and you're right, this is a bit inconsistent with the idea of "Align keywords with second word of first line". I guess the reason is simply that in the samples from real-life code that I checked, I found so many examples like that. Often, people also attempted to align the parts after the keywords, e.g. 

```ABAP
    SELECT  col1, col2
      FROM  any_dtab
      WHERE col1 < 10
      INTO  TABLE @DATA(lt_any).
```

While this is not possible with ABAP cleaner, using "add 2" usually comes quite close to it (at least as long as you don't have "ORDER BY" or "GROUP BY", which are longer). Also, relevant identifiers are (almost) all below each other, while with "add 7" …

```ABAP
    SELECT col1, col2
           FROM any_dtab
           WHERE col1 < 10
           INTO TABLE @DATA(lt_any).
```

… it feels a bit odd that "col1" is at the same position as "FROM". 

Which setting would you prefer, "add 4"?

Kind regards,
Jörg-Michael

**Comment by fabianlupa** [comment]
Maybe

```abap
SELECT FROM mara
       FIELDS matnr
       INTO TABLE ...
```

is more visually pleasing?

**Comment by jmgrassau** [comment]
Hi Fabian, 

yes, that's a bit better – but you still find a lot of (if not a majority of) non-strict syntax in the code, with the list of columns right after SELECT, and there you would get:

```ABAP
    SELECT      col1, col2
           FROM any_dtab
           WHERE col1 < 10
           INTO TABLE @DATA(lt_any).
```

which looks a bit awkward. And I don't think automated conversion to strict mode could work, because even reliably identifying @host variables is not  possible without backend access.

Kind regards,
Jörg-Michael

**Comment by ConjuringCoffee** [comment]
Like in #216, your explanation makes sense to me. 🙂 

I'm currently doing a poll internally and 2 spaces is currently in the lead. (I voted for 4 spaces for the reasons I described in my initial comment.)

Do you have an idea on how the issue with `SELECT.ENDSELECT.` could be solved? My immediate thought was to have a separate setting for it, but that might not be the best approach.

**Comment by fabianlupa** [comment]
> Do you have an idea on how the issue with SELECT.ENDSELECT. could be solved? My immediate thought was to have a separate setting for it, but that might not be the best approach.

I often see an additional blank line in those cases :/

```abap
    SELECT *
      FROM mara
      INTO @DATA(ls_mara).

      WRITE 'hello'.
    ENDSELECT.
```

And on the other hand these often get refactored to a `SELECT ... INTO TABLE` or a `SELECT SINGLE` when touched.
