### ISSUE TITLE
Feature request: Notification when active profile was not found

### ISSUE THREAD

**Issue by ConjuringCoffee** [SAP/abap-cleaner#219]
Hi Jörg-Michael, I'd like to request another new feature. 😇

The ABAP Cleaner has one "active" profile. If I delete that profile directly from my file system, the ABAP Cleaner automatically switches to another profile. Would it be possible to show a notification or an error message if this happens?

Here's where this request is coming from: I am currently sharing a profile temporarily with some colleagues. At a later point, I want to delete this profile. I might not be able to reach every colleague before deleting the profile, so I am facing the risk that they accidentally keep working with whatever profile the ABAP Cleaner automatically chooses after the deletion.

What do you think? Thanks 😄

**Comment by ConjuringCoffee** [comment]
This seems similar to: #140

**Comment by jmgrassau** [comment]
Hi ConjuringCoffee, 

that's a good idea – with the next release, you will see a message like …

![image](https://github.com/SAP/abap-cleaner/assets/79639298/6b68a38d-b2f1-4113-a8ca-e94b5e30a4f4)

… if a profile goes missing while the interactive window is open. 

By contrast, if _automated_ cleanup realizes the expected profile is missing, you get:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/34b5cd5d-cc76-4701-98e2-52f7dd918da0)

So, in this case, the code is only changed if you press Ctrl+4 again. 

The fallback is either the profile named "default", if such a profile exists, or otherwise the first profile in alphabetical order. 

Kind regards,
Jörg-Michael

**Comment by ConjuringCoffee** [comment]
Awesome - that's exactly what I wanted to see. Thanks!

**Comment by jmgrassau** [comment]
Hi ConjuringCoffee, 

this notification is now available with version 1.13.0!

Kind regards,
Jörg-Michael
