### ISSUE TITLE
Request: Support ABAP Cleaner for ABAP codes in Web Dynpro projects

### ISSUE THREAD

**Issue by flying-crane** [SAP/abap-cleaner#220]
Dear developers,

I find the ABAP Cleaner will not work for the code in Web Dynpro projects, including implementations from the **view** and **component** **controllers**.

<img width="565" alt="image" src="https://github.com/SAP/abap-cleaner/assets/32824459/56f930d8-8f1e-4288-871d-c34d6b05fb6e">

But it can work as expected in the assistance class of the Web Dynpro projects. Please help to check.

Best regards,
Henry

**Comment by jmgrassau** [comment]
Hi Henry, 

thanks for opening this issue! You're right, Eclipse seems to treat these code editors differently than the normal ABAP code editors. For those, ABAP cleaner currently defines three menus and key bindings (cp. Window -> Preferences -> General -> Keys -> search for "ABAP cleaner"):

![image](https://github.com/SAP/abap-cleaner/assets/79639298/893276e8-febf-4050-9f0f-a4778db2d8ed)

Apparently, these Web Dynpro editors are not part of the context "Editing ABAP Code", presumably because of the restriction that the code is partly read-only: 

![image](https://github.com/SAP/abap-cleaner/assets/79639298/98d333b7-95f6-4330-88ed-2ce93c867fbf)

I need to check with an ADT expert what could be done here. Currently, what you could do as a workaround:
* copy the (entire) code from the Web Dynpro editor to the clipboard, 
* open any regular ABAP code (e.g. an ABAP class) in a different editor,
* select menu "Source Code / Read-Only Preview With ABAP Cleaner…" there,
* paste your code into the ABAP cleaner UI with Ctrl+V (or menu "Code / From Clipboard"), 
* use Ctrl+A and Ctrl+C to copy the cleaned code to the clipboard,
* temporarily insert it to any text editor (e.g. Notepad),
* from there, method by method, copy the cleaned code back to the WebDynpro editor (since pasting the whole code into the WebDynpro editor won't work due to the read-only sections).

That's a bit tedious, but compared to manual cleanup, it might nevertheless save a lot of time. Alternatively, you could 
* install the [standalone version](https://github.com/SAP/abap-cleaner/releases) of ABAP cleaner, 
* open it next to ADT, and 
* use the menu "Code / [Watch and Modify Clipboard](https://github.com/SAP/abap-cleaner/blob/main/docs/usage.md#cleaning-code-with-the-stand-alone-abap-cleaner-app), which immediately replaces any section of code within the clipboard, as soon as you copy it with Ctrl+C (blocks like IF ... ENDIF must be complete). 
* With that, you could stay within the WebDynpro editor, select the content of a method, press Ctrl+C ("Watch and Modify Clipboard" then plays a 'beep') and directly replace the selection with the cleaned code using Ctrl+V. 

But that's only workarounds, of course! Let's see if a proper solution will be possible. 

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi Henry, 

good news – our ADT expert found a solution to the problem, so cleanup of WebDynpro implementations will be possible with the next release! 

There is only one small downside with this solution: Directly after starting ADT, before the ABAP cleaner plug-in is fully activated, the ABAP cleaner menus ("Source / Clean Up With Automated ABAP cleaner" etc.) will now also be enabled for editors with CDS view definitions, database table definitions etc., although ABAP cleaner does not support them. However, if you try running ABAP cleaner there, you will simply get the message "The chosen operation is not enabled", and nothing will be changed. Afterwards (or after any successful cleanup on ABAP code), those menus will be correctly grayed out for CDS view definitions, database table definitions etc. 

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi Henry,

thanks again for pointing this out – with version 1.13.1, which was just released, the ABAP cleaner menus should now be directly available for WebDynpro implementations, too! 

Unfortunately, I entered the wrong issue number #200 when committing the code changes –
[enable ABAP cleaner menus for WebDynpro implementations](https://github.com/SAP/abap-cleaner/commit/bd6a397c6ad7b1b476055e13ecef1d6abc1c1ed8) belongs to this issue, as well as [Force abapcleaner.gui plugin activation when checking handler enablement](https://github.com/SAP/abap-cleaner/commit/6583f410bd95ac1be85bd2a42bdba0a9ae74917c).

Kind regards,
Jörg-Michael
