### ISSUE TITLE
Error executing rule 'Align SELECT lists': First token 'case' unexpected for a term

### ISSUE THREAD

**Issue by this-yash** [SAP/abap-cleaner#229]
Hi,

I've been getting this error for the new cleaning rules added for aligning the SELECT lists (Screenshot Attached). It's just the case statement. If there's any way to rewrite the syntax without getting the error, please share. Else, please check if this issue is fixable. 
Also, if we can get a new option added for aligning the joins "below the SELECT clause + 2" instead of/along with "below the table name + 2", just like I did in the screenshot attached, that'd be really awesome!!
Thanks!

![image](https://github.com/SAP/abap-cleaner/assets/64050540/c259ba2d-6abb-4f0c-ac6a-bf5b0c9fe008)

**Comment by jmgrassau** [comment]
Hi Yash, 

thanks a lot for reporting this! That's definitely a bug on ABAP cleaner side (so, no reason to rewrite your code). Will look into it! 

I shall also check about the position of the JOINs. However, I'm not sure whether this will easily be possible, because these joins are not considered as an independent clause (such as FROM, WHERE, GROUP BY etc.), but as part of the FROM clause. 

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi Yash, 

this bug will be fixed with the next release.

Kind regards,
Jörg-Michael

**Comment by this-yash** [comment]
Sure, Thanks!
