### ISSUE TITLE
abap cleaner also for CDS Entities / Views?

### ISSUE THREAD

**Issue by VladGhitulescu** [SAP/abap-cleaner#231]
Hey,

the abap cleaner doesn't seem to work inside CDS Entities / Views.

Is this so or do I miss some setting?

Thanks!

Regards,
Vlad

**Comment by jmgrassau** [comment]
Hi Vlad, 

yes, this is so – CDS data definition language is simply not supported by ABAP cleaner. 

Kind regards,
Jörg-Michael

**Comment by ConjuringCoffee** [comment]
Related: #7 😉

**Comment by jmgrassau** [comment]
Hi @VladGhitulescu,

happy to say that since version 1.19.1, formatting of CDS Views / Data Definition Language is now supported by ABAP cleaner, see [Release Notes](https://github.com/SAP/abap-cleaner/blob/main/docs/release-notes.md)!

Therefore, changing the label to "new cleanup rule" (it's actually 21 rules for DDL as of now), but keeping it closed – all done! :-) (However, as #7 shows, certainly not running out of ideas for DDL, either; and then, there is also DCL …).

Kind regards,
Jörg-Michael
