### ISSUE TITLE
Alignment of AND in JOIN ... ON

### ISSUE THREAD

**Issue by vonglan** [SAP/abap-cleaner#240]
Hello, 
it was mentioned that SQL statements or not yet really in focus for ABAP Cleaner.
So I suppose, the following thing is not yet supposed to work nicely, or is it?
Rule "Align SELECT ... FROM ... JOIN", in the example, I find the position of the AND irritating:

![image](https://github.com/SAP/abap-cleaner/assets/17814756/c4a11daf-2cbc-4af2-a3b9-9b393d143a96)

The END should be aligned with the ON, or the equal signs aligned.

I could not make it work nicely with reconfiguring the rule, either.
(And anyway, in my company we will try to stick to the default.)

Best regards,
Edo

**Comment by jmgrassau** [comment]
Hi Edo, 

you're right, the equals signs in this condition should be aligned – however, when I tried your example, it worked fine. This is probably from the example code for the "Align SELECT ... FROM ... JOIN" rule, right? Then it is simply a misunderstanding: Each of those "Align SELECT …" rules only does one part of the job, and the alignment of the ON clause is done by yet another rule, the "Align logical expressions" rule. So, if you copy the example to the main window of ABAP cleaner, things should look fine, because there, all rules are executed:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/4c629f81-8e45-42fe-9f42-932998f89e10)

You can try it this way:
* either open the standalone version of ABAP cleaner, or from ADT, use menu "Source Code / Show Read-Only Preview …" (because this menu allows to paste code to the main window of the ABAP cleaner UI)
* press "Configure…" and click on the "Align SELECT ... FROM ... JOIN" rule
* select entire example code and press Ctrl+C to copy the right-hand side, or Ctrl+Shift+C to copy the left-hand side
* close "Profiles and Rules" window
* press Ctrl+V to have _all_ cleanup rules executed on the example code

Kind regards,
Jörg-Michael

**Comment by vonglan** [comment]
Hi Jörg-Michael, 
thanks for the explanation, that makes perfect sense!
Herzliche Grüße aus Lübeck,
Edo
