### ISSUE TITLE
Number of lines in "Highlight inner space changes" not always correct?

### ISSUE THREAD

**Issue by ConjuringCoffee** [SAP/abap-cleaner#25]
In the following example, the number of lines for "Highlight inner space changes" is 0, but I'd have expected it to be 1.

![image](https://github.com/SAP/abap-cleaner/assets/72548231/0887e798-ffce-4add-a687-66ff2f448c29)

If I uncheck the rule for removing lang="en", then the line number is increased to 1.

![image](https://github.com/SAP/abap-cleaner/assets/72548231/889d63d1-c34b-41a2-a277-a54f6b5bc910)

Is this a bug or this behavior intended?

**Comment by jmgrassau** [comment]
Hi ConjuringCoffee, 

wow, that's well observed… will look into it, my first impression is that this part of the code anyway needs to be reworked a bit. And yes, I can't claim that showing "0 lines" here is an intended feature :-), especially since activating and deactivating the "Highlight inner space changes" option actually changes the orange highlight of the spaces in the right-hand display. 

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi ConjuringCoffee, 

okay, this refactoring has the nice additional effect that you will now be able to deactivate even the last option, now called "Highlight text _and line_ changes" (for text changes and added/deleted lines):

![image](https://github.com/SAP/abap-cleaner/assets/79639298/b96600b4-d64e-4dac-b0f1-3fc3ba6d69e0)

This allows to completely turn off the highlighting and get an overall impression of what the cleaned code looks like. 

The above bug should also be fixed now (i.e. in the next release).

Kind regards,
Jörg-Michael

**Comment by ConjuringCoffee** [comment]
Hi Jörg-Michael, that was fast - thanks!

**Comment by ConjuringCoffee** [comment]
I can confirm that it works now.
