### ISSUE TITLE
Incorrect "TODO: variable is assigned but never used (ABAP cleaner)" comment

### ISSUE THREAD

**Issue by matthewdjb** [SAP/abap-cleaner#250]
Consider this sample code:

```
REPORT.

CLASS lcl_main DEFINITION.
  PUBLIC SECTION.
    METHODS get_timestamp
      RETURNING VALUE(r_result) TYPE timestamp.

ENDCLASS.


CLASS lcl_main IMPLEMENTATION.
  METHOD get_timestamp.
    " TODO: variable is assigned but never used (ABAP cleaner)
    DATA system_time_zone TYPE timezone.

    CALL FUNCTION 'GET_SYSTEM_TIMEZONE'
      IMPORTING timezone = system_time_zone. " Time Zone
    CONVERT DATE sy-datum TIME sy-uzeit INTO TIME STAMP r_result TIME ZONE system_time_zone.
  ENDMETHOD.
ENDCLASS.
```

Despite the fact that **system_time_zone** is used, the TODO comment is inserted.

Interestingly, this doesn't happen if the code is outside a method. E.g.
```
REPORT.

DATA r_result         TYPE timestamp.
DATA system_time_zone TYPE timezone.

CALL FUNCTION 'GET_SYSTEM_TIMEZONE'
  IMPORTING timezone = system_time_zone. " Time Zone
CONVERT DATE sy-datum TIME sy-uzeit INTO TIME STAMP r_result TIME ZONE system_time_zone.
cl_demo_output=>display_data( r_result ).

```

**Comment by ConjuringCoffee** [comment]
Are you on the latest version (1.13.1)? To my knowledge, this exact bug was fixed two days ago: #243

**Comment by matthewdjb** [comment]
What are the odds it'd be the same as something reported 5 days ago!

Yep. Works now. thanks.

**Comment by jmgrassau** [comment]
Hi Matthew, 

> What are the odds …

Yes, particularly because this bug must have been around for quite some time! But as always, we'd rather have duplicates than missing a bug or an idea, so thanks nevertheless!

Btw, your second example is not processed by the "Delete unused variables" rule at all because the rule only works on local variables (e.g. variables declared inside a FORM, FUNCTION, or METHOD as well as inside some event blocks like AT SELECTION-SCREEN). 

Kind regards,
Jörg-Michael
