### ISSUE TITLE
Add clear for export parameters at beginning of method

### ISSUE THREAD

**Issue by mraht** [SAP/abap-cleaner#254]
Export parameters should always be cleared at the first executable line of a method to avoid old, obsolete data to be exported by this very method. Sometimes a developer forgot to add such a statement.

It would be cool, if there was a rule which enabled ABAP Cleaner to check whether such a statement is already existent for all export parameters and add a clear for missing ones.

**Comment by jmgrassau** [comment]
Hi Marius,

unfortunately, the possibility to check this is a bit limited, because ABAP cleaner does not do additional backend calls, which might be needed to retrieve the method signature if it is "out of sight" (e.g. because the method is defined on an interface or in a parent class). 

Whenever the method signature is found in the same code document, the cleanup rule "Report unused parameters" indeed reports missing CLEAR: 

![image](https://github.com/SAP/abap-cleaner/assets/79639298/e0957ff6-513f-49ff-96bc-4be8d56c83bf)

I'd be hesitant, though, to automatically introduce CLEAR if it is missing, because ABAP cleaner should not change the behavior of a method. And funny things can happen, esp. if the caller passes the same variable into both EXPORTING and IMPORTING parameters. Try this with and without the CLEAR: 

```ABAP
    METHODS any_method.

    METHODS get_next_date
      importing iv_date type dats
      exporting ev_next_date type dats.

...

  METHOD any_method.
    DATA lv_date TYPE dats VALUE '20240220'.
    get_next_date( EXPORTING iv_date      = lv_date
                   IMPORTING ev_next_date = lv_date ).
    WRITE lv_date.
  ENDMETHOD.

  METHOD get_next_date.
    " CLEAR ev_next_date.
    ev_next_date = iv_date + 1.
  ENDMETHOD.
```

Kind regards,
Jörg-Michael
