### ISSUE TITLE
Feature Request: Omit the parameter name in single parameter calls

### ISSUE THREAD

**Issue by jelliottp** [SAP/abap-cleaner#26]
There is not currently a check for this in codePal, but it is included in the [style guide](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md#omit-the-parameter-name-in-single-parameter-calls).

**Comment by jmgrassau** [comment]
Hi Josh, 

that would indeed be nice – but I'm afraid this is not possible, because ABAP cleaner works without backend requests, so it can't "see" more than the code document provided to it. Particularly, ABAP cleaner cannot request signatures, DDIC information etc. from the backend, so if it sees a method call such as

```ABAP
  lo_any_instance->any_method( iv_param1 = 1 ).
```

it cannot safely change this into 

```ABAP
  lo_any_instance->any_method( 1 ).
```

because the method signature might look like this:

```ABAP
    METHODS any_method
      IMPORTING iv_param0 TYPE i OPTIONAL
                iv_param1 TYPE i OPTIONAL
                iv_param2 TYPE i OPTIONAL.
```

(leading to the syntax error "The parameter name can be omitted only if the method has only one non-optional IMPORTING parameter or one optional IMPORTING parameter identified by "PREFERRED PARAMETER".")

Sorry, that's indeed a limitation – but on the other hand makes everything else happen really fast! 

Kind regards,
Jörg-Michael
