### ISSUE TITLE
"Variable assigned but never used" : False positive for MESSAGE INTO

### ISSUE THREAD

**Issue by HuprichT** [SAP/abap-cleaner#275]
Hi, 

given the following Code:
```
CLASS lcl_ DEFINITION.
  PUBLIC SECTION.
    METHODS initialize.
ENDCLASS.

CLASS lcl_ IMPLEMENTATION.
  METHOD initialize.
    DATA log_msg TYPE string.

    MESSAGE w001(zbc) INTO log_msg.
  ENDMETHOD.
ENDCLASS.
```

After running the ABAP Cleaner, it messages that this Variable is never used, but it is clearly used here:
![image](https://github.com/SAP/abap-cleaner/assets/45813255/d211a7fc-87de-456b-b83a-3d2287ec1afc)

This would have led to serious problems if we had activated the setting to automatically delete unsued variables.

**Comment by jmgrassau** [comment]
Hello HuprichT, 

thanks for opening this issue! First of all, no worries about deletion: This case "assigned but never used" has a setting of its own, which does not include deletion of the variable declaration (because that would of course lead to a syntax error):

![image](https://github.com/SAP/abap-cleaner/assets/79639298/d2ee9818-66a4-42c5-a542-e76ecd81722d)

And even if ABAP cleaner would ever by mistake delete such a declaration, you would get a syntax error and could undo all changes done by ABAP cleaner with Ctrl+Z (or from version history if needed). 

The comment is actually not wrong, but maybe a bit unclear: "assigned but never used" means that you _write_ to a local variable, but never _read_ from it, which often points to copy errors, mixed-up variables in formulas etc.  Example:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/1ce5109b-cd09-4b45-a866-9614061bc90a)

So, "never used" refers to a missing _read_ access here, although, arguably, you also "use" a variable when you _write_ to it. But yes, in this specific case ```log_msg``` is nevertheless needed for MESSAGE to work as intended. Ideally, what you should do is add the pragma ```##NEEDED``` to the declaration. With that, the ABAP cleaner comment will not come up – and in fact, the comment created earlier will automatically be removed by ABAP cleaner if you press Ctrl+4 again:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/c9ebb1d4-31f0-4c9b-bee5-a125c6e81672)

If you use an inline declaration for the variable here, ABAP cleaner already detects this situation and adds a hint to the comment:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/daa48ed5-2313-4498-86c3-73383c091be1)

So, let me see if this detection can be extended a bit to also add such a hint in your scenario (i.e. an upfront declaration of a variable that is only assigned in a MESSAGE statement but never evaluated)! 

Come to think about it, I could also try to add an option to automatically introduce a ##NEEDED pragma in this case. 

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi HuprichT, 

with the next release, the cleanup rule "Delete unused variables" will have a new option "Action for variables only assigned in MESSAGE ... INTO":

![image](https://github.com/SAP/abap-cleaner/assets/79639298/258bd4db-a0bc-49c5-ac14-9769b7efa8d7)

The new default, "add pragma ##NEEDED", will have the following effect:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/f93786fe-84c5-4f9f-8512-15fb7beabe46)

The previous behavior would be "add TODO comment":

![image](https://github.com/SAP/abap-cleaner/assets/79639298/8c70ddd3-2949-44c8-9cd2-2cd25ce930c8)

In both cases, ABAP cleaner can now identify these cases with upfront declarations as well (while previously, this specific "TODO … add pragma ##NEEDED" comment was only created for ```MESSAGE ... INTO DATA(...)```, i.e. for inline declarations). 

Kind regards,
Jörg-Michael
