### ISSUE TITLE
Feature request: Custom CDS names for rule "Use CamelCase for known CDS names"

### ISSUE THREAD

**Issue by ConjuringCoffee** [SAP/abap-cleaner#281]
Hi Jörg-Michael, would it be possible to somehow provide a list of custom CDS names to the rule "Use CamelCase for known CDS names"? Maybe an additional file that can be handled independently from the profile? 😉

**Comment by jmgrassau** [comment]
Hi ConjuringCoffee, 

haha, I was literally waiting for this suggestion to come up, and you did it within less than 1 hour after the release! 

Yes, this should be doable, and I already tried to consider this as a possible enhancement while implementing the current functionality. 

My idea would be to 
* specify a subfolder of the "profiles" folder (so it can be synchronized as part of team profiles), along with file prefixes for one or multiple text files containing custom view names or field names, respectively (e.g. "profiles/CamelCase/ViewNames*.txt" and "profiles/CamelCase/FieldNames*.txt) 
* specify a format for these text files – probably simply "MyCustomFieldName<linefeed>"
* allow each profile to activate or deactivate custom CDS names (but always using the same text files)
* prioritize these custom names between the "approved" ones and the "known" ones from SAP. So, if you have
  * "CompanyCode" approved at SAP
  * "Companycode" and "AnyFieldname" in your custom files 
  * "AnyFieldName" known (but not approved) at SAP,

  then "CompanyCode" (from SAP) and "AnyFieldname" (from custom files) would override the other variants. 
* maybe even provide some sample ABAP code for downloading this information from your SAP system (tables DD02B and DD03ND)

Would that make sense? Some open question include 
* whether custom names should be checked against naming rules and filtered out if they violate them (e.g. with respect to allowed prefixes and suffixes, or if they start with a lower case letter like "anyFieldName"), 
* what to do if custom files contain contradictory names (e.g. both "AnyFieldname" and "Anyfieldname")
* whether to prioritize personal custom files in %APPDATA% higher or lower than synchronized team custom files. 

Kind regards,
Jörg-Michael

**Comment by ConjuringCoffee** [comment]
Thank you for the quick and elaborate response! Your basic idea is sound, but to me it would be important to be able to have the settings independently from the profile. Imagine one of the following scenarios:

- An open source project wants to provide the ABAP Cleaner profile and the names of its CDS views 
(e.g. how I currently do it via my [ABAP Cleaner Recommendation](https://github.com/ConjuringCoffee/abap-cleaner-recommendation))
- A developer works for multiple customers and must therefore already manually switch between multiple profiles 
(because the ABAP Cleaner settings are saved independently from the workspace, see #211)

**Comment by jmgrassau** [comment]
Hi ConjuringCoffee, 

just to be sure that I understand you correctly: Where and how would a user then configure the location of their fiels with custom CDS names? And once configured, they would always be valid, regardless of the selected profile? 

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi ConjuringCoffee, 

version 1.20.0, which was just released, now offers to enter custom view and field names in rule "Use CamelCase for known CDS names" (which are then also used in other rules, namely "Use CamelCase in test class for CDS view" (new) and "Use CamelCase for known entity and field names"):

![image](https://github.com/user-attachments/assets/b32fd99b-ca38-4a8b-90fe-9154205f2f42)

This means that any text file mentioned here is expected in folder of the respective profile (local or synchronized). If the text file is not found, nothing happens, otherwise, the view / field names from this file will be considered in cleanup (ABAP cleaner always checks whether the files were updated and reloads them if needed). 

The files can simply contain a list of CamelCase names, one per line. Leading and trailing spaces are ignored, and if any invalid character (such as * or " or any other) is found, the rest of the line is considered to be a comment (so you can enter comment lines, line-end comments and empty lines as needed to structure the file).

Since the profile itself just stores these two file names, it is completely up to you whether you reuse the same text files for all the profiles or use specific files for each profile or a subset of profiles. When you export a profile to a different folder, its text files are _not_ automatically exported with the profile. 

On a local profile, pressing the "Open …" button will directly open the text file in your standard text editor (as configured in the OS for extension .txt). On synchronized profiles, it will open the profiles folder – but then you can of course open and modify the .txt files as you (or anyone that can access the synchronized folder) like. And you could of course automatically populate those files from the names already used in your system, e.g. with the following selects (plus additional filters as needed): 

```ABAP
    " view names
    SELECT
      FROM dd02b AS b
             INNER JOIN
               dd02bnd AS bnd ON b~strucobjn = bnd~strucobjn
      FIELDS b~strucobjn,
             b~strucobjn_raw
      WHERE b~as4local = 'A'
        AND (    bnd~dbobjkind  = 'VIEW' " skip 'AMDP', 'APVI'
              OR bnd~dbobjkind IS INITIAL )
      INTO TABLE @DATA(lt_node)
      PACKAGE SIZE @gc_package_size.

      " collect CamelCase view names from lt_node[ ]-strucobjn_raw, applying further filters, if needed
    ENDSELECT.
    " download CamelCase view names to text file

    " field names
    SELECT FROM dd03nd
      FIELDS fieldname,
             strucobjn,
             fieldname_raw
      WHERE as4local = 'A'
      INTO TABLE @DATA(lt_node)
      PACKAGE SIZE @gc_package_size.

      " collect CamelCase field names from lt_node[ ]-fieldname_raw, applying further filters, if needed
    ENDSELECT.
    " download CamelCase field names to text file
```

As you can see, from ABAP cleaner side, this is not ABAP project-specific, but for that, maybe it helps that the profile that was last used is stored workspace-specifically? So you could have a distinct profile (and therefore, if needed, distinct custom name text files) per workspace? 

Kind regards,
Jörg-Michael

**Comment by ConjuringCoffee** [comment]
Awesome, thank you! You even went the extra mile by providing a code snippet on how to read the view and field names via ABAP. You impress again!

**Comment by vonglan** [comment]
Just saw this now. This is fantastic! I wished for this back in 2022. Already wanted to build a clumsy workarond for myself, because I have a longer program with CDS fieldnames, that was started before the ABAP Pretty Printer could be configured not to mess with mixedCase variable names.
