### ISSUE TITLE
Format code on save in ADT / Eclipse

### ISSUE THREAD

**Issue by robinbaeurle** [SAP/abap-cleaner#3]
Hi,

When saving an ABAP file in ADT/Eclipse, I would want the ABAP Cleaner to run automatically, formatting the file first and then saving it.

Similar tools for JavaScript or Java already have such functionality and I consider it very practical.

Is it possible to add a feature to format the code on save?

BR
Robin

**Comment by jmgrassau** [comment]
Hi Robin, 

thanks very much for opening this issue – the very first on Open Source ABAP cleaner! 

I do understand your point – it's always a good thing to reduce frequent clicks. What would make things a bit tricky here is that you may not always want to apply ABAP cleaner to the _whole_ code document, because that could e.g. contain dozens of methods, resulting in lots of changed objects on your transport. Rather, we would somehow have to identify the parts of the documents that were changed (e.g. on method level) and clean only those. 

This information must be available somewhere (after all, it is shown in the right-hand sidebar of the ADT editor), but I'm not sure how easily we could retrieve it from the ABAP cleaner plug-in, and whether an ABAP cleaner action could then indeed be "injected" into the save process. I asked a colleague who would know better than me and will get back! 

Kind regards,
Jörg-Michael

**Comment by jelliottp** [comment]
I agree that this would be a nice feature! Regarding this: 
> What would make things a bit tricky here is that you may not always want to apply ABAP cleaner to the whole code document
>
My opinion here is that this is not necessarily a problem, and is how fixes should ideally be made. Even though the transport system allows you to lock a single method for transport, tools like codePal and open checks are still going to scan and report errors on the entire class. 

One compromise may be to allow this as a setting on the tool for users to choose their preferred option.

**Comment by jmgrassau** [comment]
Hi Robin and Josh, 

meanwhile, I learned from a colleague that there is currently no technical way for ABAP cleaner to hook into the save process – so, unfortunately, have to close this as "out of scope" for now. Thanks nevertheless for the idea!

Kind regards,
Jörg-Michael

**Comment by jelliottp** [comment]
FYI, I have used other plugins such as ABAP CI which are able to do this (it does pretty printer & removes unused variables upon activation). I am not sure if the implementation is different however.
