### ISSUE TITLE
Preferences ABAP Cleaner

### ISSUE THREAD

**Issue by emmeneggerdani** [SAP/abap-cleaner#301]
Hello
Is it possible to enter profile or cleaner settings, If there is no development object in the editor / open?
Didn't find the possibility... maybe provide a link within eclipse-preferences? Theres only the way via source-code menu, but this is only shown, when source code is open...

Regards,
Daniel

**Comment by jmgrassau** [comment]
Hi Daniel, 

you're right, there is currently no way to directly access ABAP cleaner configuration, i.e. you have to open an ABAP code document and "pretend" that you want to clean it. (I usually use menu "Source Code / Show Read-Only Preview With ABAP Cleaner…" in such a case, thus making sure that the source code is not changed). 

ABAP cleaner indeed has a bit of an individual approach here, because it has a system-wide (i.e. cross-Eclipse workspace) configuration which is stored in the application data on your local machine. 

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi Daniel and ConjuringCoffee, 

thanks, ConjuringCoffee, for the link to the related issue, I think we should continue the discussion there to avoid duplicates. 

Kind regards,
Jörg-Michael
