### ISSUE TITLE
line_exists not seen as use of  a method importing parameter

### ISSUE THREAD

**Issue by matthewdjb** [SAP/abap-cleaner#307]
`
    METHODS remove_headers_not_in_orders
      EXPORTING i_order_headers TYPE ty_headers
      CHANGING  x_orders        TYPE ty_orders.`

`  METHOD remove_headers_not_in_orders.
    " TODO: parameter I_ORDER_HEADERS is never cleared or assigned (ABAP cleaner)

    LOOP AT x_orders ASSIGNING FIELD-SYMBOL(<order>).
      CHECK NOT line_exists( i_order_headers[ aufnr = <order>-raufnr ] ).
      DELETE x_orders.
    ENDLOOP.
  ENDMETHOD.`

The TODO is spurios, because of i_order_headers is used in the line_exists function.

**Comment by jmgrassau** [comment]
Hi Matthew, 

as far as I can see, this works as expected: The problem is that this parameter is declared as an EXPORTING parameter, so you would expect that inside the method, it is either CLEARed or set to some value. If it is only used insider the method, the parameter should be declared as an IMPORTING parameter. With that, ABAP cleaner would not introduce this TODO (but even remove it automatically):

![image](https://github.com/SAP/abap-cleaner/assets/79639298/8be7305f-43bb-415a-9078-e1dcb98029cc)

Kind regards,
Jörg-Michael

**Comment by matthewdjb** [comment]
How embarrassing. I didn't spot that.

Thanks for correcting my code! :-)

**Comment by jmgrassau** [comment]
Happy to help :-)

And I guess it's easy to miss, because with a variable named I_… you'd be sure to have an IMPORTING variable. So maybe it would help to rephrase the message to "TODO: *EXPORTING* parameter … is never cleared or assigned (ABAP cleaner)"?

**Comment by matthewdjb** [comment]
Yes, that would be clearer.
