### ISSUE TITLE
type structure in Function Moudle doesnt work 

### ISSUE THREAD

**Issue by pardonmycode** [SAP/abap-cleaner#309]
The keywords **type** in function modules seem not to have the same behavior as in classes.

ABAP cleaner	Version: 1.16.1	
Had this: 

`FUNCTION Z_WM_RFC_EXAMPLE `
 ` IMPORTING  `
 ` VALUE(I_e) TYPE i  `
 ` VALUE(I_EXAMPLE) TYPE i  `
 ` VALUE(I_something) TYPE i  `

should be:

`FUNCTION Z_WM_RFC_EXAMPLE` 
`   IMPORTING` 
`     VALUE(I_e)         TYPE i  ` 
`     VALUE(I_EXAMPLE)   TYPE i  ` 
`     VALUE(I_something) TYPE i  `

**Comment by jmgrassau** [comment]
Hi pardonmycode (that's a nice user name :-), 

unfortunately, there would be no point in ABAP cleaner changing the layout of a FUNCTION declaration, because as soon as you'd save the changed code, the layout would switch back to what is was before (you can try it out by manually changing the layout and then saving the code!) 

From my understanding, this is because the FUNCTION's signature is stored in a different (form-based) way, unlike a METHOD or FORM signature, which is part of the source code like any statement in the METHOD or FORM body. 

Kind regards,
Jörg-Michael
