### ISSUE TITLE
String template is proposed for JSON string without any need

### ISSUE THREAD

**Issue by apanys** [SAP/abap-cleaner#323]
Hi,

for this code:

```abap
DATA(lv_json) = `{"a":"b", ` && `"c":{}}`.
```

abap-cleaner proposes without any need string templates:

```abap
DATA(lv_json) = |\{"a":"b", "c":\{\}\}|.
```

On one side, the unnecessary string templates causes runtime costs and on the other
side the JSON syntax becomes quite hard to read because of the escaping of the bracelets.

Kind regards
André

**Comment by jmgrassau** [comment]
Hi André, 

thanks for opening this! Not sure about the runtime costs: unlike the literal operator & (which is executed only once during compile time), the concatenation operator && is executed each time at runtime, so there is a runtime cost to the original concatenation. By contrast, I'd assume that the escaped characters in the string template are already replaced at compile time, so the string template is already complete at runtime (but I'm not an expert here). 

However, readability certainly suffers in this case. I think there could be different approaches here:
1. There is already the option "Embed operands … if result is shorter / shorter or equal". This option does not consider the code length changes due to escape characters yet. If we enhanced it accordingly, some extreme cases would be avoided (not your example, though, because the result is still shorter than the original code).
2. We could add an option to avoid string templates if more than X escape characters would have to be introduced. 
3. Or there could be an option to only introduce string templates if there are embedded expressions, but not if multiple string literals are concatenated – assuming that there was a (readability) reason for using separate literals in the original code. So none of the following examples would be converted:
   ![image](https://github.com/SAP/abap-cleaner/assets/79639298/4c8a2d6e-7baf-4251-aec0-5d4010cff929)

Which do you think would fit your request best?

Kind regards,
Jörg-Michael

**Comment by apanys** [comment]
Hi Jörg-Michael,

Yes, in my real coding the JSON is quite long and spanning multiple lines because of the line limit of ABAP,
therefore I added the concatenation operator. 

I prefer option 3.
Thanks.

Kind regards
André

**Comment by jmgrassau** [comment]
Hi André, 

thanks again – in version 1.18.0, which was just released, the cleanup rule "Use string templates to assemble text" now has this option:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/28193ba1-632f-45dd-b485-5910340561e8)

If activated, only the second line of the example will be changed:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/db2f19df-53b2-49f5-95eb-5dbe42951294)

Kind regards,
Jörg-Michael

**Comment by apanys** [comment]
Thanks a lot Jörg-Michael.

Kind regards
André
