### ISSUE TITLE
variable is assigned but never used not working correctly

### ISSUE THREAD

**Issue by Ennowulff** [SAP/abap-cleaner#331]
Hey there!

please see the following code

```
CLASS zcl_demo_01 DEFINITION
  PUBLIC FINAL
  CREATE PUBLIC.

  PUBLIC SECTION.
    METHODS replace_text_in
      IMPORTING
        mailtext        TYPE string
        with            TYPE clike
        if              TYPE clike
        text            TYPE clike OPTIONAL
      RETURNING
        VALUE(r_result) TYPE string.

  PRIVATE SECTION.
    TYPES: BEGIN OF _changed_parts,
             one   TYPE abap_bool,
             two   TYPE abap_bool,
             three TYPE abap_bool,
           END OF _changed_parts.

    DATA changed_parts TYPE _changed_parts.
ENDCLASS.


CLASS zcl_demo_01 IMPLEMENTATION.
  METHOD replace_text_in.
    ASSIGN COMPONENT if OF STRUCTURE changed_parts TO FIELD-SYMBOL(<field>).
    IF sy-subrc > 0.
      RETURN.
    ENDIF.

    " TODO: variable is assigned but never used (ABAP cleaner)
    DATA(findstr) = |${ if }%|.
    r_result = mailtext.
    DATA(replacestr) = |<p>{ with }{ COND #( WHEN text IS SUPPLIED THEN |: <b>{ text }</b>| ELSE `` ) }</p>|.
    IF <field> IS NOT INITIAL.
      REPLACE findstr WITH replacestr INTO r_result.
    ELSE.
      REPLACE findstr WITH `` INTO r_result.
    ENDIF.
  ENDMETHOD.
ENDCLASS.
```

ABAP cleaner thinks that the variable findstr is not used, but it is by REPLACE.

**Comment by jmgrassau** [comment]
Hi Enno, 

thanks for reporting this bug! If you activate the menu "Highlight / Write Positions", you can see that this happened because ABAP cleaner misinterpreted the [obsolete syntax of REPLACE substring WITH new INTO dobj](https://help.sap.com/doc/abapdocu_latest_index_htm/latest/en-US/abapreplace_obsolete.htm): 

![image](https://github.com/SAP/abap-cleaner/assets/79639298/71d2c18c-75bd-4ea1-b950-b022946253e1)

The write position really is ```ev_result```, and after fixing that, the issue will not come up anymore in the next release:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/b0e9f304-d112-495c-8b08-4d7e050014e9)

Kind regards,
Jörg-Michael

**Comment by Ennowulff** [comment]
Thanks for fast fixing of this glitch, @jmgrassau ! ❤️
