### ISSUE TITLE
Delete unused variables

### ISSUE THREAD

**Issue by JoachimEck** [SAP/abap-cleaner#333]
Hey again,

sorry but today it is a strange day 😄

When I use the ABAP Cleaner, it doesn't delete the unused variables in some cases. I have set up an example. ![image](https://github.com/SAP/abap-cleaner/assets/101569831/51f7c45c-871f-4ad6-9734-be0995a16c4c) ![image](https://github.com/SAP/abap-cleaner/assets/101569831/275ddf11-dc95-4bb9-bcf7-cd4b3957b7dd) It moves the used variables, so it seems to recognize that the others are not used.  If I remove the "ASSIGN" commands, it deletes everything. 
Here is the entire profile again: [profile.zip](https://github.com/user-attachments/files/15985034/profile.zip)

Sorry for so much work today. But I love your tool!

Thanks.

Best regards, Joachim

**Comment by jmgrassau** [comment]
Hi Joachim, 

thanks for opening this! Unfortunately, this is "no defect", because as soon as ABAP cleaner finds a dynamic ```ASSIGN ('...')``` (or macro usage or test injection), it skips the "Delete unused variables" rule altogether for the current method. While things are obvious in your example, it would generally be too difficult (and in many cases, impossible) to determine which variables are used dynamically and which aren't. 

But please keep going! Maybe you just have some pieces of rare syntax in today's code, which ABAP cleaner has never been confronted with! 

Kind regards,
Jörg-Michael

P.S.: Other rules that may be skipped in such cases are "Use FINAL for immutable variables", "Remove needless CLEAR", and "Report unused parameters".

**Comment by JoachimEck** [comment]
Hi Jörg-Michael,

thank you very much for your explanation. Now I can understand that.

Best regards,
Joachim
