### ISSUE TITLE
Syntax Error caused by rule "Simplify a chain with one element" inside Includes

### ISSUE THREAD

**Issue by openPhiL** [SAP/abap-cleaner#372]
Hello Jörg-Michael, 
The following scenario is leading to a wrong cleaning: 
Rule: "Simplify a chain with one element" with the default options

When we apply the cleaner to this code: 
```abap
DATA:
  "! Only used for declaring select-option
  gv_serial_number TYPE gernr.
```
it will produce this code: 
```abap
"! Only used for declaring select-option DATA gv_serial_number TYPE gernr.
```

Important: This seems to only happen because the object that we found is an include where the DATA:-line is literally the first line of the object. Any other command or even comment above the DATA will prevent this error. 

Thank you for looking into it! 
PhiL

**Comment by jmgrassau** [comment]
Hi PhiL, 

ooops … Nice finding! Internally, ABAP cleaner always stores the number of line breaks above (and spaces left of) each token. At document start this can be 0, and this special case case was obviously not considered here. Will be fixed with the next release! 

![image](https://github.com/user-attachments/assets/2c162dad-77cd-4b5e-8643-2cf073991bda)

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi openPhiL, 

thanks for this bug reporting – this shouldn't come up again with version 1.20.1!

Kind regards,
Jörg-Michael
