### ISSUE TITLE
Two concluding dots distort the alignment

### ISSUE THREAD

**Issue by blackfish5** [SAP/abap-cleaner#379]
OK:
![image](https://github.com/user-attachments/assets/e6485aae-616f-4331-a3d1-73c197658113)

NOT OK:
![image](https://github.com/user-attachments/assets/e235ab31-831b-4a19-9ef4-614cdfcdd335)

**Comment by jmgrassau** [comment]
Hi blackfish5, 

this happened because between the two METHODS statements, there was another statement (consisting of a "." only) that separated the alignment sections. But I changed that now, so, in the next release, alignment will also happen across empty "." statements. 

Kind regards,
Jörg-Michael

P.S.: Any reason why you deactivated the "Remove empty commands" rule? This would have cleaned away the superfluous "." before the alignment :-)

**Comment by jmgrassau** [comment]
Hi blackfish5, 

thanks for providing this example – alignment should now work with version 1.21.0, which was just released!

Kind regards,
Jörg-Michael
