### ISSUE TITLE
Remove unnecessary parameters name from 'Exporting' keyword and indentation

### ISSUE THREAD

**Issue by GPR8** [SAP/abap-cleaner#39]
Hi all! thank you for this great tool!

It would be nice, if you could enhance the 'Omit optional Exporting' option, so when a method has only one exporting parameter the input parameter name doesn't show up. Like this:

**lv_value = get_value( value1 ).**

Instead of:

**lv_value = get_value( iv_value1 = value1 ).**

Also, on indentation point of view it would be nice to have an option to align the parameters next to parenthesis like this:

**lv_value = get_value(  iv_value1 = value1
....................................... iv_value2 = value2 ).**
(the dots it's just to keep the indentation as I want to show you)

 instead of this:

**lv_value = get_value(  
      iv_value1 = value1
      iv_value2 = value2 ).**

(Image as it is attached). 

Thank you!!

![indentation example](https://github.com/SAP/abap-cleaner/assets/39055226/3a7ea4cb-109b-4d48-b250-26570cd2b242)

**Comment by RicardoLadeiro** [comment]
I would also support the option to exclude the import parameter name when there is only one required import parameter. However, I don't know to what extent there isn't a technical limitation here, since for that it would be necessary to access the definition of the class/method that is called. 
Thumbs up for this one!

**Comment by ConjuringCoffee** [comment]
The parameter name topic has been discussed already here: #26 

Regarding the indentation topic, rule "Align parameters and components" should already do this. Can you please check?

**Comment by jmgrassau** [comment]
Hi GPR8, 

no need to apologize, we'd rather have a duplicate issue than missing out on a bug or a good idea! 

>  it would be nice to have an option to align the parameters next to parenthesis like this

Actually assigning "documentation" to this issue, because I think the documentation could point out a bit better that the examples really just show the effects of the currently displayed rule – while in "real life", you will get the combined effect of all active rules (which btw. are executed on the code in the exact order shown in the "Rules in Current Profile" list). 

> trying to update for 1.2.1 release version

Hm, that's odd, actually this should work as soon as you click Eclipse menu "Help / Check for Updates". Could you check in menu "Window / Preferences" -> Install/Update -> Available Software Sites whether ABAP cleaner was added here?

![image](https://github.com/SAP/abap-cleaner/assets/79639298/51b72e76-4ea8-41b4-b04d-4634cc720576)

Kind regards,
Jörg-Michael

**Comment by GPR8** [comment]
Hi Jorg,

Thanks for getting back to me!
About that, yes I confirm I have it installed, but every time I try to update nothing happens
![image](https://github.com/SAP/abap-cleaner/assets/39055226/a346e9ef-1100-48bb-a309-88ef53a8f404)
![image](https://github.com/SAP/abap-cleaner/assets/39055226/b0c1532e-6ce6-4bd1-8c4a-f9aadabb71a0)

Let me know your thoughts on this.

Thanks!
Guilherme

**Comment by GPR8** [comment]
Hey @jmgrassau , @ConjuringCoffee,

I've managed to find out the update problem! we need to apply the solution described here (SAP Note 3131747 - "Unable to read repository at ..." during installation of ABAP Development Tools or required plugins ) https://www.eclipse.org/forums/index.php/t/1108242/
After apply this ans restart Eclipse I was able to get the latest version :)
**"Solution
Assuming that you can access the repository URL in your browser in Windows, you have the following option to import the certificate into your Eclipse:

Adapt the eclipse.ini file, in order to use the Microsoft Certificate Trust Store, in which the missing certificate is included:

Add the following lines into the "eclipse.ini" file right after the line:"-vmargs"

-Djavax.net.ssl.trustStore=NUL

-Djavax.net.ssl.trustStoreType=Windows-ROOT"**

maybe this is something you can point into the rest of the community. 
Hope this helps somehow!
Thank you!
Cheers all!

**Comment by jelliottp** [comment]
Hi @GPR8, it appears you ran into the issue already mentioned on the [known installation issues](https://github.com/SAP/abap-cleaner/blob/main/docs/installation-issues.md). II can't explain why you didn't have this problem when first installing and only updating though.

**Comment by GPR8** [comment]
@jmgrassau @jelliottp 
Probably it would be nice add also this point to Installation Issues in the next release. Just a suggestion :)

Cheers!

**Comment by jmgrassau** [comment]
Hi @GPR8, 

excellent, will add that to the installation issues documentation!

Kind regards,
Jörg-Michael
