### ISSUE TITLE
Remove the self-reference me->: Does not work in interface methods

### ISSUE THREAD

**Issue by ConjuringCoffee** [SAP/abap-cleaner#41]
Hi Jörg-Michael, the self-reference `me->` is not removed in interface methods.

Here's an example I re-created using local objects:

```
INTERFACE lif_test.
  METHODS from_interface.
ENDINTERFACE.


CLASS lcl_test DEFINITION CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES lif_test.

  PROTECTED SECTION.

  PRIVATE SECTION.
    DATA mv_value TYPE i.

    METHODS in_class.
ENDCLASS.


CLASS lcl_test IMPLEMENTATION.
  METHOD lif_test~from_interface.
    me->mv_value = 1.
  ENDMETHOD.

  METHOD in_class.
    me->mv_value = 1.
  ENDMETHOD.

ENDCLASS.
```

Here's the result:
![image](https://github.com/SAP/abap-cleaner/assets/72548231/78b92003-341d-426a-b408-710ea52a7663)

**Comment by jmgrassau** [comment]
Hi ConjuringCoffee, 

generally, ABAP cleaner can only remove "me->" if the method signature is known – otherwise, it could not be sure in your example whether ```mv_value``` is both an attribute and at the same time an exporting parameter; in such a case, ```me->``` would of course have to be kept in order to refer to the attribute (not the parameter). 

That's why this rule usually does not work on interface methods, where the signature is usually "out of sight". Admittedly, though, that's not the case for local interfaces as in your example – so the rule could indeed be enhanced to process these cases!

Kind regards,
Jörg-Michael

**Comment by ConjuringCoffee** [comment]
Hmm, I did not consider that. That's unfortunate - thanks for the explanation!

**Comment by ConjuringCoffee** [comment]
I suggest adding this to the documentation of the rule. I just noticed that this limitation also impacts attributes inherited from another global class.

**Comment by jmgrassau** [comment]
Hi ConjuringCoffee, 

I now added some documentation:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/3c401eb6-f579-42da-9d76-e1ae6b89d9dc)

Also, local interfaces are now correctly considered, including aliases and "cascading" cases (interfaces implementing other interfaces and defining aliases for them etc.):

![image](https://github.com/SAP/abap-cleaner/assets/79639298/6eb6e4f7-5b85-47a7-b8e5-e3329c1f92a5)

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi ConjuringCoffee, 

as mentioned before, the perfect solution is unfortunately not possible here as long as we do not introduce backend calls to ABAP cleaner; however, I think this is as good as it gets for now! 

Kind regards,
Jörg-Michael
