### ISSUE TITLE
No highlights for "Features added after v1.3.0" 

### ISSUE THREAD

**Issue by ConjuringCoffee** [SAP/abap-cleaner#46]
The highlighting for v1.3.0 doesn't seem to work: Nothing is highlighted.

![image](https://github.com/SAP/abap-cleaner/assets/72548231/7cb6eb99-2539-4223-b1ca-223d427f97d3)

The rule "Add missing parameters to ABAP Doc" is new, right? I'd have expected it to be marked here.

**Comment by jmgrassau** [comment]
Hi ConjuringCoffee, 

this is not a bug but a feature :-) Note that it says "Features added _after_ v1.3.0". The idea as follows: 

* Let's say you start with "Features added after v1.2.0", which currently shows 1 new cleanup rule (highlighted in green) and 3 enhanced rules (highlighted in yellow, the affected options highlighted in green). 
* You may want to check whether you like the default settings for the new features and adjust them as you like. 
* Then, after checking everything up to the current state, you can select "Features added after v1.3.0" (which _currently_ highlights nothing, because it is the current version). 
* Now suppose you are busy doing other things, and after several weeks (and several updates) you get back to ABAP cleaner, which is by then maybe at version 1.7.0. However, you forgot which version you last checked. Luckily, ABAP cleaner remembers your setting, so the selection will still be "Highlight: Features added after v1.3.0" – and now, multiple rules are highlighted for you to check. 
* After that, you can again set to "Features added after v1.7.0". 

By contrast, if you select "Highlight: Off", it will always remain off, even after updates.

Kind regards,
Jörg-Michael

P.S.: If you could think of how this idea could be expressed in words short enough to fit into the Highlight combo box, please let me know…
