### ISSUE TITLE
Eclipse ADT - Update Site not reachable?

### ISSUE THREAD

**Issue by richardbruenning** [SAP/abap-cleaner#69]
Hi, 

when we try to add the plugin to eclipse adt via install new software the URL https://sap.github.io/abap-cleaner/updatesite is not reachable. 

Any solution for this?

Best Regards Richard

**Comment by jmgrassau** [comment]
Hi Richard, 

the site works for me (and many others), so it can't be the site itself. Which Eclipse version do you use? And have you tried the solution to the [Known Issues](../blob/main/docs/installation-issues.md) "Error 'Unable to read repository ... PKIX path building failed'"? It seems that this issue comes up with different kinds of messages.

Kind regards,
Jörg-Michael

**Comment by richardbruenning** [comment]
Thank you, that was the Problem

**Comment by jmgrassau** [comment]
Hi Richard, 

excellent, thanks for confirming this! I shall then add this message "URL not reachable" to the documentation of known installation issues as well.

Kind regards,
Jörg-Michael
