### ISSUE TITLE
Alignment differences in pretty printer versus abap cleaner

### ISSUE THREAD

**Issue by fabianlupa** [SAP/abap-cleaner#9]
Hi,

are you supposed to disable alignments by pretty printer if you use abap cleaner? They correct each other for me in the default settings. Or maybe the pretty printer was adjusted in a higher release so they are the same there?

Pretty Printer:
```abap
CLASS zabc_fs_method_enum DEFINITION
  PUBLIC
  FINAL
  CREATE PRIVATE.

  PUBLIC SECTION.
    TYPES instances TYPE SORTED TABLE OF REF TO zabc_fs_method_enum WITH UNIQUE KEY table_line.

    CLASS-DATA:
      file_exists            TYPE REF TO zabc_fs_method_enum READ-ONLY,
      read_file_bin          TYPE REF TO zabc_fs_method_enum READ-ONLY,
      read_file_text         TYPE REF TO zabc_fs_method_enum READ-ONLY,
      write_file_bin         TYPE REF TO zabc_fs_method_enum READ-ONLY,
      get_directory_contents TYPE REF TO zabc_fs_method_enum READ-ONLY,
      create_directory       TYPE REF TO zabc_fs_method_enum READ-ONLY,
      delete_directory       TYPE REF TO zabc_fs_method_enum READ-ONLY,
      get_default_codepage   TYPE REF TO zabc_fs_method_enum READ-ONLY,
      get_separator          TYPE REF TO zabc_fs_method_enum READ-ONLY,
      get_connection_info    TYPE REF TO zabc_fs_method_enum READ-ONLY,
      BEGIN OF partial_reader READ-ONLY,
        read_file_to_buffer_bin  TYPE REF TO zabc_fs_method_enum,
        read_file_to_buffer_text TYPE REF TO zabc_fs_method_enum,
      END OF partial_reader,
      BEGIN OF partial_writer READ-ONLY,
        write_buffer_to_file_bin  TYPE REF TO zabc_fs_method_enum,
        write_buffer_to_file_text TYPE REF TO zabc_fs_method_enum,
      END OF partial_writer.

    DATA value TYPE abap_methname READ-ONLY.

    CLASS-METHODS class_constructor.
    CLASS-METHODS get_instances RETURNING VALUE(result) TYPE instances.

  PROTECTED SECTION.
  PRIVATE SECTION.
    CLASS-DATA:
      enum_instances TYPE instances.
    METHODS:
      constructor IMPORTING method_name TYPE abap_methname.
ENDCLASS.
```

ABAP Cleaner
```abap
CLASS zabc_fs_method_enum DEFINITION
  PUBLIC
  FINAL
  CREATE PRIVATE.

  PUBLIC SECTION.
    TYPES instances TYPE SORTED TABLE OF REF TO zabc_fs_method_enum WITH UNIQUE KEY table_line.

    CLASS-DATA:
      file_exists                 TYPE REF TO zabc_fs_method_enum READ-ONLY,
      read_file_bin               TYPE REF TO zabc_fs_method_enum READ-ONLY,
      read_file_text              TYPE REF TO zabc_fs_method_enum READ-ONLY,
      write_file_bin              TYPE REF TO zabc_fs_method_enum READ-ONLY,
      get_directory_contents      TYPE REF TO zabc_fs_method_enum READ-ONLY,
      create_directory            TYPE REF TO zabc_fs_method_enum READ-ONLY,
      delete_directory            TYPE REF TO zabc_fs_method_enum READ-ONLY,
      get_default_codepage        TYPE REF TO zabc_fs_method_enum READ-ONLY,
      get_separator               TYPE REF TO zabc_fs_method_enum READ-ONLY,
      get_connection_info         TYPE REF TO zabc_fs_method_enum READ-ONLY,
      BEGIN OF partial_reader READ-ONLY,
        read_file_to_buffer_bin   TYPE REF TO zabc_fs_method_enum,
        read_file_to_buffer_text  TYPE REF TO zabc_fs_method_enum,
      END OF partial_reader,
      BEGIN OF partial_writer READ-ONLY,
        write_buffer_to_file_bin  TYPE REF TO zabc_fs_method_enum,
        write_buffer_to_file_text TYPE REF TO zabc_fs_method_enum,
      END OF partial_writer.

    DATA value TYPE abap_methname READ-ONLY.

    CLASS-METHODS class_constructor.
    CLASS-METHODS get_instances RETURNING VALUE(result) TYPE instances.

  PROTECTED SECTION.
  PRIVATE SECTION.
    CLASS-DATA:
      enum_instances TYPE instances.
    METHODS:
      constructor IMPORTING method_name TYPE abap_methname.
ENDCLASS.
```

**Comment by jmgrassau** [comment]
Hi Fabian, 

thanks for reporting this issue – this should be fixed in the next release (version 1.2), meaning that alignment of "normal" variables (in your example, FILE_EXISTS, READ_FILE_BIN, …, GET_CONNECTION_INFO) will be independent from alignment of structures. 

In case of nested structures, I actually added a new option to the "Align declarations" rule: 

![image](https://github.com/SAP/abap-cleaner/assets/79639298/45ac04f0-37cb-4ba0-943d-140603553c80)

As you will see in the example for this rule, this will produce

a) align outer structure with inner
![image](https://github.com/SAP/abap-cleaner/assets/79639298/76e4a5c3-ac3a-41b9-b257-bf35b2745d7f)

b) align outer structure independently (like Pretty Printer)
![image](https://github.com/SAP/abap-cleaner/assets/79639298/ccbbccee-de4f-4db3-bf49-c79df86852da)

c) align each section independently
![image](https://github.com/SAP/abap-cleaner/assets/79639298/28d3c916-3867-4145-8db2-ab5d323c6893)

Option b) would be the new default to avoid inconsistencies with what Pretty Printer does. 

However, generally speaking, ABAP cleaner pretty much covers the current scope of Pretty Printer (or rather, ABAP Formatter), so my typical sequence of shortcuts has actually changed from "Shift+F1 – Ctrl+F2 – Ctlr+F3" into "Ctrl+4 – Ctrl+F2 – Ctlr+F3", meaning that I hardly use the Pretty Printer anymore (in fact, Ctrl+4 was selected as a shortcut to make this a convenient sequence). 

In a few cases, ABAP cleaner even intentionally deviates from Pretty Printer behavior, esp. in the "Indent lines" rule: Since comments are supposed to refer to the code below (not above) them, IMHO, ABAP cleaner alignment is better in cases such as:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/01848a84-a6d8-4db7-8141-e7dbadb82ed7)

Kind regards,
Jörg-Michael

**Comment by fabianlupa** [comment]
Thanks for the response and the details! I agree I am much more content with the formatting done by ABAP Cleaner, especially since ABAP Formatter is dependent on the backend release and offers very little customization. I'll try retraining my muscle memory ;)

**Comment by ConjuringCoffee** [comment]
If you want to avoid retraining your muscle memory, you can just change the key bindings in the Eclipse properties 😉 

Properties > General > Keys
