### ISSUE TITLE
Bug: Keyword text is not taken as keyword when letters are entered as value

### ISSUE THREAD

**Issue by jan-jezek** [SAP/abap-cleaner#95]
The rule "Convert upper and lower case" is not working correctly for keyword "text", if the value has any letter in it.
Imagine two situations:
`WRITE text-042`
`WRITE text-a42`
For  the first one "text" will be converted to "TEXT" with default setting.
But in the second case "text" is not converted.

IMHO this is bug as Pretty Print converts it to upper case and abaplint reports it as error if not converted.

![image](https://github.com/SAP/abap-cleaner/assets/17530797/b74a96b2-5443-4dd0-9e4a-f7e4b7db9fe9)

**Comment by jmgrassau** [comment]
Hi Jan, 

thanks for reporting this! 

For some background: Code bits that aren't separated with a space – such as ```lo_any_instance->any_method(``` or ```ms_struc-component-subcomponent``` – are usually stored in one single token in ABAP cleaner, because except for display colors, there is no reason to ever tear them apart. In this case, however, some special processing was needed, because ```TEXT-a42``` contains both a keyword and an identifier (unlike the other examples above).

The issue will be fixed in the next release, and coloring is now also adjusted to ADT:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/c4ce5eaa-d493-41d5-8749-5af2409e045c)

As in ADT, the result depends on the settings for keywords and identifiers, so you could also get:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/6fbfd64a-3de8-43bb-98bf-603cef454fbc)

![image](https://github.com/SAP/abap-cleaner/assets/79639298/5a1368c8-8cf2-40d7-abb0-06b413e1c7d1)

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi Jan, 

thanks again for opening this issue! This should now be fixed with version 1.5.3, which was just released.

Kind regards,
Jörg-Michael
